--LOGIN AS :- PLADMIN
--EXECUTION :- 13

SET SERVEROUTPUT ON;
CLEAR SCREEN;

--CUSTOMER PACKAGE

GRANT EXECUTE ON spms_customer_management_pkg TO PL_USER1;
GRANT EXECUTE ON spms_slot_booking_pkg TO PL_USER1;


GRANT SELECT ON CUST_VAL TO PL_USER1;

GRANT SELECT ON VEHICLE_VAL TO PL_USER1;

GRANT SELECT ON SLOT_BOOKING_VAL TO PL_USER1;

GRANT SELECT ON PAYMENT_VAL TO PL_USER1;

GRANT SELECT ON CHECKIN_VAL TO PL_USER1;

GRANT SELECT ON FEEDBACK_VAL TO PL_USER1;




--MANAGER PACKAGE


GRANT SELECT ON ADDRESS_VAL TO PL_MANAGER1;
GRANT SELECT ON PARKING_LOT_ID_VAL TO PL_MANAGER1;
GRANT SELECT ON FLOOR_ID_VAL TO PL_MANAGER1;
GRANT SELECT ON PARKING_SLOT_ID_VAL TO PL_MANAGER1;

GRANT EXECUTE ON spms_manager_management_pkg TO PL_MANAGER1;