--------------------------------------Execute below statement to grant access to Manager and User to specific tables---------------------------------
--Execution Order 7
--Execute using PLADMIN

set SERVEROUTPUT on
CLEAR SCREEN;
SET AUTOCOMMIT ON;

--Grant permissions for Tables to PLManager
GRANT SELECT,INSERT,UPDATE ON ADDRESS TO PL_MANAGER1;
GRANT SELECT,INSERT,UPDATE ON PARKING_LOT TO PL_MANAGER1;
GRANT SELECT,INSERT,UPDATE ON FLOOR TO PL_MANAGER1;
GRANT SELECT,INSERT,UPDATE ON PARKING_SLOT TO PL_MANAGER1;
GRANT SELECT ON CUSTOMER TO PL_MANAGER1;
GRANT SELECT ON VEHICLE TO PL_MANAGER1;
GRANT SELECT ON SLOT_BOOKING TO PL_MANAGER1;
GRANT SELECT ON PAYMENT TO PL_MANAGER1;
GRANT SELECT ON CHECK_IN TO PL_MANAGER1;
GRANT SELECT ON FEEDBACK TO PL_MANAGER1;

--Grant Permission for Views to PLManager 


GRANT SELECT ON parking_slots_filled TO PL_MANAGER1;
GRANT SELECT ON parking_slots_vacant TO PL_MANAGER1;
GRANT SELECT ON customer_feedback TO PL_MANAGER1;
GRANT SELECT ON peak_hours TO PL_MANAGER1;
GRANT SELECT ON off_peak_hours TO PL_MANAGER1;
GRANT SELECT ON parking_lot_performance_by_day TO PL_MANAGER1;
GRANT SELECT ON NO_SHOW_BOOKINGS TO PL_MANAGER1;




--Grant Permission for Tables to PLUser

GRANT SELECT ON ADDRESS TO PL_USER1;
GRANT SELECT ON PARKING_LOT TO PL_USER1;
GRANT SELECT ON FLOOR TO PL_USER1;
GRANT SELECT ON PARKING_SLOT TO PL_USER1;
GRANT SELECT,INSERT,UPDATE ON CUSTOMER TO PL_USER1;
GRANT SELECT,INSERT,UPDATE ON VEHICLE TO PL_USER1;
GRANT SELECT,INSERT,UPDATE ON SLOT_BOOKING TO PL_USER1;
GRANT SELECT,INSERT ON PAYMENT TO PL_USER1;
GRANT SELECT ON CHECK_IN TO PL_USER1;
GRANT SELECT,INSERT,UPDATE ON FEEDBACK TO PL_USER1;

--Grant Permission to Views
GRANT SELECT ON customer_vehicles TO PL_USER1;
GRANT SELECT ON booking_details TO PL_USER1;
GRANT SELECT ON booking_history TO PL_USER1;
GRANT SELECT ON parking_lot_rating TO PL_USER1;
GRANT SELECT ON available_slots TO PL_USER1;


